name: Docker

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: philanthropydatacommons/service

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  test-build-image:
    # This job should run only on pull requests, not on main
    if: ${{ github.ref != 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Build with node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - run: npm ci
      - run: npm run build
      - run: npm prune --omit=dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build but do not push and do not write to cache
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache

  build-and-publish-image:
    # This job should run only on main, not on pull requests
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - run: echo VERSION="$(git log -1 --date=unix --pretty=format:'%cd' | date --utc '+%Y%m%d')"-"$(git log -1 --pretty=format:'%h')" >> "$GITHUB_ENV"
      - name: Build with node
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version
      - run: npm ci
      - run: npm run build
      - run: npm prune --omit=dev
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Wait for lint, test, and other workflows to succeed
        uses: kachick/wait-other-jobs@v3
        timeout-minutes: 24
        with:
          wait-list: |
            [
              {
                "workflowFile": "lint.yml"
              },
              {
                "workflowFile": "test.yml"
              },
              {
                "workflowFile": "sdk.yml"
              }
            ]
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:buildcache,mode=max
